import type { Locale } from "@/i18n/config";
import { siteContact } from "@/content/site-contact";

export type CorePageKey = "about" | "event" | "success" | "talentbook" | "contact" | "apply" | "privacy";
type PageContent = { eyebrow:string; title:string; intro:string; sections:Array<{title:string;body:string;items?:string[]}>; cta?:{label:string;href:string} };

const en:Record<CorePageKey,PageContent>={
  about:{eyebrow:"About SoccerX Camp",title:"A serious stage for ambitious footballers.",intro:"SoccerX Camp connects young players with international coaching, competitive football and professional scouting perspectives.",sections:[{title:"The purpose",body:"Create a focused environment where players can train, compete and be evaluated with clarity."},{title:"The network",body:"SoccerX Camp is organized with Soccer and More, bringing international football management, coaching and scouting perspectives into one focused environment."},{title:"Our standard",body:"Clear organization, demanding football and respectful communication with players and families."}],cta:{label:"Contact the team",href:"/contact"}},
  event:{eyebrow:"Event archive · Germany",title:"SoccerX Trials Germany ’26",intro:"Archive of the international football trials held in Germany from 6–12 April 2026 for players born from 2008 through 2011.",sections:[{title:"On the pitch",body:"Structured training and competitive matches were designed to show how players responded technically, tactically and mentally."},{title:"The setting",body:"The campaign included accommodation at Fun4You in Wiesloch, near Heidelberg, alongside the event's football programme."},{title:"Event record",body:"This page is retained as a historical record. Applications for the April 2026 event are closed.",items:["Dates: 6–12 April 2026","Eligible birth years: 2008–2011","Location: Germany","Status: completed"]}]},
  success:{eyebrow:"Success archive",title:"Progress earned on and beyond the pitch.",intro:"A selection of documented trials, signings and professional opportunities connected with the SoccerX Camp network.",sections:[{title:"Opportunity in motion",body:"Each story represents a different step: being observed, earning a trial, joining a club or continuing development in a professional environment."},{title:"Built on the pitch",body:"The archive connects the camp experience with real football pathways while preserving the original WordPress media and published context."}],cta:{label:"Learn about the camp",href:"/about"}},
  talentbook:{eyebrow:"Player archive",title:"Talentbook",intro:"A focused archive for approved player material and historical SoccerX Camp publications.",sections:[{title:"2023 archive",body:"The WXR references English and Greek 2023 publications and one PDF attachment. The file remains unavailable until the media manifest is reviewed and approved."},{title:"Next edition",body:"Future editions should use accessible web profiles and an optional verified PDF download rather than an image-only publication."}]},
  contact:{eyebrow:"Contact",title:"Start the conversation.",intro:"Questions about the Germany trials, participation or SoccerX Camp can be directed to the existing public contacts below.",sections:[{title:"Greece",body:siteContact.phones[0].label},{title:"Germany",body:siteContact.phones[1].label},{title:"Email",body:siteContact.emails.map(item=>item.label).join("\n")}]},
  apply:{eyebrow:"Participation",title:"Prepare your application.",intro:"The rebuilt application workflow is intentionally not accepting submissions yet. The legacy form handles information about potentially minor athletes and requires an approved privacy and consent process first.",sections:[{title:"Expected information",body:"Athlete and guardian identity, birth date, current club, position, city and contact details. Physical measurements and free-form notes remain under data-minimization review."},{title:"Before submissions open",body:"The owner must approve the event terms, privacy notice, consent text, retention period, recipients and deletion process."},{title:"Contact meanwhile",body:"Use the published phone numbers or email addresses on the Contact page for current participation enquiries."}],cta:{label:"Contact SoccerX Camp",href:"/contact"}},
  privacy:{eyebrow:"Privacy",title:"Privacy information",intro:"The contact form uses the details you submit only so the SoccerX Camp team can receive and answer your enquiry.",sections:[{title:"Contact enquiries",body:"Your name, email address, optional phone number, subject and message are sent by email to the published SoccerX Camp contacts. The website does not store these submissions in an application database."},{title:"Participation boundary",body:"The contact form is not a participation application and should not be used to send medical information, identity documents or other sensitive data. A separate approved notice and consent process is required before athlete applications open."},{title:"Your request",body:"You may use the published contact details to ask about access, correction or deletion of information supplied in an enquiry."}]}
};
const el:Record<CorePageKey,PageContent>={
  about:{eyebrow:"Σχετικά με το SoccerX Camp",title:"Μια σοβαρή σκηνή για φιλόδοξους ποδοσφαιριστές.",intro:"Το SoccerX Camp συνδέει νέους αθλητές με διεθνή προπόνηση, ανταγωνιστικό ποδόσφαιρο και επαγγελματική οπτική scouting.",sections:[{title:"Ο σκοπός",body:"Ένα συγκεντρωμένο περιβάλλον όπου οι παίκτες προπονούνται, αγωνίζονται και αξιολογούνται με σαφήνεια."},{title:"Το δίκτυο",body:"Το SoccerX Camp διοργανώνεται με τη Soccer and More, συνδυάζοντας διεθνή εμπειρία management, προπονητική και scouting σε ένα απαιτητικό περιβάλλον."},{title:"Το πρότυπό μας",body:"Σαφής οργάνωση, απαιτητικό ποδόσφαιρο και υπεύθυνη επικοινωνία με παίκτες και οικογένειες."}],cta:{label:"Επικοινωνία με την ομάδα",href:"/contact"}},
  event:{eyebrow:"Αρχείο διοργάνωσης · Γερμανία",title:"SoccerX Trials Γερμανία ’26",intro:"Αρχείο των διεθνών ποδοσφαιρικών trials που πραγματοποιήθηκαν στη Γερμανία από 6–12 Απριλίου 2026 για παίκτες γεννημένους από το 2008 έως το 2011.",sections:[{title:"Στο γήπεδο",body:"Οι οργανωμένες προπονήσεις και οι ανταγωνιστικοί αγώνες σχεδιάστηκαν ώστε να αναδείξουν τεχνική, τακτική και νοοτροπία."},{title:"Η τοποθεσία",body:"Η διοργάνωση περιλάμβανε διαμονή στο Fun4You στο Wiesloch, κοντά στη Χαϊδελβέργη, παράλληλα με το αγωνιστικό πρόγραμμα."},{title:"Αρχείο διοργάνωσης",body:"Η σελίδα διατηρείται ως ιστορικό αρχείο. Οι αιτήσεις για τη διοργάνωση του Απριλίου 2026 έχουν κλείσει.",items:["Ημερομηνίες: 6–12 Απριλίου 2026","Έτη γέννησης: 2008–2011","Τοποθεσία: Γερμανία","Κατάσταση: ολοκληρώθηκε"]}]},
  success:{eyebrow:"Αρχείο επιτυχιών",title:"Πρόοδος μέσα και έξω από το γήπεδο.",intro:"Μια επιλογή από καταγεγραμμένα trials, υπογραφές και επαγγελματικές ευκαιρίες που συνδέονται με το δίκτυο του SoccerX Camp.",sections:[{title:"Η ευκαιρία σε κίνηση",body:"Κάθε ιστορία αποτυπώνει ένα διαφορετικό βήμα: αξιολόγηση, trial, ένταξη σε ομάδα ή συνέχιση της εξέλιξης σε επαγγελματικό περιβάλλον."},{title:"Χτισμένο στο γήπεδο",body:"Το αρχείο συνδέει την εμπειρία του camp με πραγματικές ποδοσφαιρικές διαδρομές, διατηρώντας το αρχικό υλικό και το δημοσιευμένο πλαίσιο."}],cta:{label:"Σχετικά με το camp",href:"/about"}},
  talentbook:{eyebrow:"Αρχείο παικτών",title:"Talentbook",intro:"Ένα οργανωμένο αρχείο για εγκεκριμένο υλικό παικτών και παλαιότερες εκδόσεις του SoccerX Camp.",sections:[{title:"Αρχείο 2023",body:"Το WXR αναφέρει αγγλικές και ελληνικές εκδόσεις του 2023 και ένα PDF. Το αρχείο παραμένει κλειστό μέχρι την έγκριση του media manifest."},{title:"Επόμενη έκδοση",body:"Οι επόμενες εκδόσεις πρέπει να χρησιμοποιούν προσβάσιμα web profiles και προαιρετικό επαληθευμένο PDF."}]},
  contact:{eyebrow:"Επικοινωνία",title:"Ας ξεκινήσουμε τη συζήτηση.",intro:"Για ερωτήσεις σχετικά με τη Γερμανία, τη συμμετοχή ή το SoccerX Camp χρησιμοποιήστε τα υπάρχοντα δημόσια στοιχεία.",sections:[{title:"Ελλάδα",body:siteContact.phones[0].label},{title:"Γερμανία",body:siteContact.phones[1].label},{title:"Email",body:siteContact.emails.map(item=>item.label).join("\n")}]},
  apply:{eyebrow:"Συμμετοχή",title:"Προετοίμασε την αίτησή σου.",intro:"Η νέα ροή δεν δέχεται ακόμη αιτήσεις. Η παλιά φόρμα αφορά δεδομένα πιθανώς ανήλικων αθλητών και απαιτεί πρώτα εγκεκριμένη διαδικασία απορρήτου και συγκατάθεσης.",sections:[{title:"Αναμενόμενα στοιχεία",body:"Στοιχεία αθλητή και κηδεμόνα, ημερομηνία γέννησης, ομάδα, θέση, πόλη και επικοινωνία. Οι σωματικές μετρήσεις και οι ελεύθερες σημειώσεις εξετάζονται ως προς την ελαχιστοποίηση δεδομένων."},{title:"Πριν ανοίξουν οι αιτήσεις",body:"Πρέπει να εγκριθούν οι όροι, η πολιτική απορρήτου, η συγκατάθεση, η περίοδος διατήρησης, οι αποδέκτες και η διαδικασία διαγραφής."},{title:"Επικοινωνία τώρα",body:"Χρησιμοποιήστε τα τηλέφωνα ή τα email στη σελίδα Επικοινωνίας."}],cta:{label:"Επικοινωνία",href:"/contact"}},
  privacy:{eyebrow:"Απόρρητο",title:"Πληροφορίες απορρήτου",intro:"Η φόρμα επικοινωνίας χρησιμοποιεί τα στοιχεία που υποβάλλετε μόνο ώστε η ομάδα του SoccerX Camp να λάβει και να απαντήσει στο μήνυμά σας.",sections:[{title:"Μηνύματα επικοινωνίας",body:"Το ονοματεπώνυμο, το email, το προαιρετικό τηλέφωνο, το θέμα και το μήνυμά σας αποστέλλονται μέσω email στις δημοσιευμένες επαφές του SoccerX Camp. Η ιστοσελίδα δεν αποθηκεύει τις υποβολές σε βάση δεδομένων εφαρμογής."},{title:"Όριο συμμετοχής",body:"Η φόρμα επικοινωνίας δεν αποτελεί αίτηση συμμετοχής και δεν πρέπει να χρησιμοποιείται για ιατρικές πληροφορίες, έγγραφα ταυτοποίησης ή άλλα ευαίσθητα δεδομένα. Πριν ανοίξουν οι αιτήσεις αθλητών απαιτείται ξεχωριστή εγκεκριμένη ενημέρωση και διαδικασία συγκατάθεσης."},{title:"Το αίτημά σας",body:"Μπορείτε να χρησιμοποιήσετε τα δημοσιευμένα στοιχεία επικοινωνίας για αίτημα πρόσβασης, διόρθωσης ή διαγραφής πληροφοριών που δώσατε μέσω επικοινωνίας."}]}
};
export function getCorePage(locale:Locale,key:CorePageKey){return(locale==="el"?el:en)[key]}
