import type { Locale } from "@/i18n/config";
import { siteContact } from "@/content/site-contact";

export type CorePageKey = "about" | "event" | "success" | "talentbook" | "contact" | "apply" | "privacy";
type PageContent = { eyebrow:string; title:string; intro:string; sections:Array<{title:string;body:string;items?:string[]}>; cta?:{label:string;href:string} };

const en:Record<CorePageKey,PageContent>={
  about:{eyebrow:"About SoccerX Camp",title:"A serious stage for ambitious footballers.",intro:"SoccerX Camp connects young players with international coaching, competitive football and professional scouting perspectives.",sections:[{title:"The purpose",body:"Create a focused environment where players can train, compete and be evaluated with clarity."},{title:"The people",body:"The legacy site identifies Tasos Maragozidis, Nickolay Guido, Dimitris Petkakis and Dora Ioakeimidou as key members. Roles and biographies remain subject to final owner approval."},{title:"Our standard",body:"Clear organization, demanding football and respectful communication with players and families."}],cta:{label:"Explore Germany ’26",href:"/events/germany-2026"}},
  event:{eyebrow:"Current event · Germany",title:"SoccerX Trials Germany ’26",intro:"International football trials planned for 6–12 April 2026 in Germany for players born from 2008 through 2011.",sections:[{title:"On the pitch",body:"Structured training and competitive matches designed to show how players respond technically, tactically and mentally."},{title:"The setting",body:"The legacy campaign identifies accommodation at Fun4You in Wiesloch, near Heidelberg. Final itinerary and accommodation terms require owner confirmation."},{title:"Prepare",body:"Participants are advised to carry a European Health Insurance Card. Travel, payment and cancellation terms must be confirmed before applications open.",items:["Dates: 6–12 April 2026","Eligible birth years: 2008–2011","Location: Germany","Applications are not yet active on this rebuilt site"]}],cta:{label:"Application information",href:"/apply"}},
  success:{eyebrow:"Legacy success archive",title:"Progress earned on and beyond the pitch.",intro:"The previous website records players and professionals connected with trials, signings and development opportunities. Every public claim and image will be verified before migration.",sections:[{title:"Evidence before promotion",body:"Names, clubs, dates, outcomes and image permissions must be owner-approved before individual stories are published."},{title:"The future format",body:"Approved stories will become structured profiles with a clear date, outcome, source and media provenance."}],cta:{label:"Learn about the camp",href:"/about"}},
  talentbook:{eyebrow:"Player archive",title:"Talentbook",intro:"A focused archive for approved player material and historical SoccerX Camp publications.",sections:[{title:"2023 archive",body:"The WXR references English and Greek 2023 publications and one PDF attachment. The file remains unavailable until the media manifest is reviewed and approved."},{title:"Next edition",body:"Future editions should use accessible web profiles and an optional verified PDF download rather than an image-only publication."}]},
  contact:{eyebrow:"Contact",title:"Start the conversation.",intro:"Questions about the Germany trials, participation or SoccerX Camp can be directed to the existing public contacts below.",sections:[{title:"Greece",body:siteContact.phones[0].label},{title:"Germany",body:siteContact.phones[1].label},{title:"Email",body:siteContact.emails.map(item=>item.label).join("\n")}]},
  apply:{eyebrow:"Participation",title:"Prepare your application.",intro:"The rebuilt application workflow is intentionally not accepting submissions yet. The legacy form handles information about potentially minor athletes and requires an approved privacy and consent process first.",sections:[{title:"Expected information",body:"Athlete and guardian identity, birth date, current club, position, city and contact details. Physical measurements and free-form notes remain under data-minimization review."},{title:"Before submissions open",body:"The owner must approve the event terms, privacy notice, consent text, retention period, recipients and deletion process."},{title:"Contact meanwhile",body:"Use the published phone numbers or email addresses on the Contact page for current participation enquiries."}],cta:{label:"Contact SoccerX Camp",href:"/contact"}},
  privacy:{eyebrow:"Privacy",title:"Privacy information",intro:"A production privacy notice will be published before any contact or participation data is collected by the rebuilt application.",sections:[{title:"Current boundary",body:"This foundation does not accept, persist or transmit form submissions."},{title:"Required policy",body:"The final notice must identify the controller, purposes, legal basis, recipients, retention, rights, security measures and special handling for minors."}]}
};
const el:Record<CorePageKey,PageContent>={
  about:{eyebrow:"Σχετικά με το SoccerX Camp",title:"Μια σοβαρή σκηνή για φιλόδοξους ποδοσφαιριστές.",intro:"Το SoccerX Camp συνδέει νέους αθλητές με διεθνή προπόνηση, ανταγωνιστικό ποδόσφαιρο και επαγγελματική οπτική scouting.",sections:[{title:"Ο σκοπός",body:"Ένα συγκεντρωμένο περιβάλλον όπου οι παίκτες προπονούνται, αγωνίζονται και αξιολογούνται με σαφήνεια."},{title:"Οι άνθρωποι",body:"Η παλιά ιστοσελίδα αναφέρει τους Τάσο Μαραγκοζίδη, Nickolay Guido, Δημήτρη Πετκάκη και Δώρα Ιωακειμίδου. Οι ρόλοι και οι βιογραφίες χρειάζονται τελική έγκριση."},{title:"Το πρότυπό μας",body:"Σαφής οργάνωση, απαιτητικό ποδόσφαιρο και υπεύθυνη επικοινωνία με παίκτες και οικογένειες."}],cta:{label:"Γερμανία ’26",href:"/events/germany-2026"}},
  event:{eyebrow:"Τρέχουσα διοργάνωση · Γερμανία",title:"SoccerX Trials Γερμανία ’26",intro:"Διεθνή ποδοσφαιρικά trials που προγραμματίζονται για 6–12 Απριλίου 2026 για παίκτες γεννημένους από το 2008 έως το 2011.",sections:[{title:"Στο γήπεδο",body:"Οργανωμένες προπονήσεις και ανταγωνιστικοί αγώνες που αναδεικνύουν τεχνική, τακτική και νοοτροπία."},{title:"Η τοποθεσία",body:"Η παλιά καμπάνια αναφέρει διαμονή στο Fun4You στο Wiesloch, κοντά στη Χαϊδελβέργη. Το τελικό πρόγραμμα και οι όροι χρειάζονται επιβεβαίωση."},{title:"Προετοιμασία",body:"Συνιστάται Ευρωπαϊκή Κάρτα Ασφάλισης Ασθενείας. Οι όροι ταξιδιού, πληρωμής και ακύρωσης πρέπει να επιβεβαιωθούν πριν ανοίξουν οι αιτήσεις.",items:["Ημερομηνίες: 6–12 Απριλίου 2026","Έτη γέννησης: 2008–2011","Τοποθεσία: Γερμανία","Οι online αιτήσεις δεν έχουν ενεργοποιηθεί"]}],cta:{label:"Πληροφορίες συμμετοχής",href:"/apply"}},
  success:{eyebrow:"Αρχείο επιτυχιών",title:"Πρόοδος μέσα και έξω από το γήπεδο.",intro:"Η παλιά ιστοσελίδα καταγράφει trials, μεταγραφές και ευκαιρίες ανάπτυξης. Κάθε δημόσιος ισχυρισμός και εικόνα θα επαληθευτεί πριν δημοσιευτεί.",sections:[{title:"Τεκμηρίωση πριν την προβολή",body:"Ονόματα, ομάδες, ημερομηνίες, αποτελέσματα και δικαιώματα εικόνας χρειάζονται έγκριση."},{title:"Η νέα μορφή",body:"Οι εγκεκριμένες ιστορίες θα γίνουν δομημένα προφίλ με ημερομηνία, αποτέλεσμα, πηγή και προέλευση πολυμέσων."}],cta:{label:"Σχετικά με το camp",href:"/about"}},
  talentbook:{eyebrow:"Αρχείο παικτών",title:"Talentbook",intro:"Ένα οργανωμένο αρχείο για εγκεκριμένο υλικό παικτών και παλαιότερες εκδόσεις του SoccerX Camp.",sections:[{title:"Αρχείο 2023",body:"Το WXR αναφέρει αγγλικές και ελληνικές εκδόσεις του 2023 και ένα PDF. Το αρχείο παραμένει κλειστό μέχρι την έγκριση του media manifest."},{title:"Επόμενη έκδοση",body:"Οι επόμενες εκδόσεις πρέπει να χρησιμοποιούν προσβάσιμα web profiles και προαιρετικό επαληθευμένο PDF."}]},
  contact:{eyebrow:"Επικοινωνία",title:"Ας ξεκινήσουμε τη συζήτηση.",intro:"Για ερωτήσεις σχετικά με τη Γερμανία, τη συμμετοχή ή το SoccerX Camp χρησιμοποιήστε τα υπάρχοντα δημόσια στοιχεία.",sections:[{title:"Ελλάδα",body:siteContact.phones[0].label},{title:"Γερμανία",body:siteContact.phones[1].label},{title:"Email",body:siteContact.emails.map(item=>item.label).join("\n")}]},
  apply:{eyebrow:"Συμμετοχή",title:"Προετοίμασε την αίτησή σου.",intro:"Η νέα ροή δεν δέχεται ακόμη αιτήσεις. Η παλιά φόρμα αφορά δεδομένα πιθανώς ανήλικων αθλητών και απαιτεί πρώτα εγκεκριμένη διαδικασία απορρήτου και συγκατάθεσης.",sections:[{title:"Αναμενόμενα στοιχεία",body:"Στοιχεία αθλητή και κηδεμόνα, ημερομηνία γέννησης, ομάδα, θέση, πόλη και επικοινωνία. Οι σωματικές μετρήσεις και οι ελεύθερες σημειώσεις εξετάζονται ως προς την ελαχιστοποίηση δεδομένων."},{title:"Πριν ανοίξουν οι αιτήσεις",body:"Πρέπει να εγκριθούν οι όροι, η πολιτική απορρήτου, η συγκατάθεση, η περίοδος διατήρησης, οι αποδέκτες και η διαδικασία διαγραφής."},{title:"Επικοινωνία τώρα",body:"Χρησιμοποιήστε τα τηλέφωνα ή τα email στη σελίδα Επικοινωνίας."}],cta:{label:"Επικοινωνία",href:"/contact"}},
  privacy:{eyebrow:"Απόρρητο",title:"Πληροφορίες απορρήτου",intro:"Πλήρης πολιτική θα δημοσιευτεί πριν συλλεχθούν δεδομένα επικοινωνίας ή συμμετοχής.",sections:[{title:"Τρέχον όριο",body:"Η παρούσα έκδοση δεν δέχεται, αποθηκεύει ή αποστέλλει φόρμες."},{title:"Απαιτούμενη πολιτική",body:"Η τελική ενημέρωση πρέπει να καλύπτει υπεύθυνο επεξεργασίας, σκοπούς, νομική βάση, αποδέκτες, διατήρηση, δικαιώματα και ειδική μεταχείριση ανηλίκων."}]}
};
export function getCorePage(locale:Locale,key:CorePageKey){return(locale==="el"?el:en)[key]}
